### ISSUE TITLE
Missing Factory instance for scala.Stream (2.12)

### ISSUE THREAD

**Issue by djspiewak** [scala/scala-collection-compat#183] opened 2019-02-13 22:49 UTC
Not entirely sure if this is the right place for this; I could file it under fs2, as well. Either way, it appears that there is no instance `Factory[A, Stream[A]]`, which in turn causes some source compatibility issues in packages (such as fs2) which have migrated to collection-compat.

No, I don't make any excuses for the use of `scala.Stream`. Legacy code. Uggghhhh.

Anyway, is this omission intentional?

**Comment by djspiewak** [comment] 2019-02-14 02:53
After a bit of hunting, it appears this may be a type inference issue somewhere. `Stream[_]` (the existential, not the type constructor) is not being considered a subtype of `Nothing` for the purposes of locating a `CanBuildFrom` which can satisfy `Factory`'s alias.

**Comment by julienrf** [comment] 2019-02-18 08:52
> Anyway, is this omission intentional?

No, it’s not.

>  `Stream[_]` (the existential, not the type constructor) is not being considered compatible with `Nothing` for the purposes of locating a `CanBuildFrom` which can satisfy `Factory`'s alias.

Then that should be the case with all other collection types? They all define an implicit `[A]CanBuildFrom[Coll, A, CC[A]]`, where `Coll = CC[_]`, and `CC[_]` is the collection type constructor (e.g., `List`).

**Comment by djspiewak** [comment] 2019-02-18 16:45
That's what I would have suspected. I really have no idea what's special about `Stream`. I'll see if I can come up with a better minimization. Right now, my minimizer is using it via the `to` function on `fs2.CompileOps`.

**Comment by szeiger** [comment] 2019-04-04 16:47
I cannot reproduce this. In the 2.12.2 REPL:

```
scala> import scala.collection.generic.CanBuildFrom
import scala.collection.generic.CanBuildFrom

scala> type Factory[-A, +C] = CanBuildFrom[Nothing, A, C] // same as in collection-compat
defined type alias Factory

scala> def f[A] = implicitly[Factory[A, Stream[A]]]
f: [A]=> Factory[A,Stream[A]]

scala> f[Int]
res6: Factory[Int,Stream[Int]] = scala.collection.immutable.Stream$StreamCanBuildFrom@45790cb
```

**Comment by szeiger** [comment] 2019-04-05 11:36
Probably a duplicate of https://github.com/scala/scala-collection-compat/issues/137 (which I cannot reproduce in the REPL, either)

**Closed** 2019-04-05 15:06 UTC
