### ISSUE TITLE
Create rich docs

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/scala-collection-compat#324] opened 2020-04-23 08:35 UTC
Julien mentions at https://github.com/scala/scala-collection-compat/pull/319#discussion_r413108179

> Actually, we don’t really have rich docs… Maybe we should add more documentation, saying what is supported, what is not, what you need to import, etc., but that’s another issue I believe…

Now it's actually another issue.

**Comment by SethTisue** [comment] 2020-09-03 01:18
duplicate of #67

**Closed by SethTisue** 2020-09-03 01:18 UTC
